DROP TABLE IF EXISTS TBL_ORDER;
  
CREATE TABLE TBL_ORDER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_name VARCHAR(250) NOT NULL,
  order_date VARCHAR(250) NOT NULL,
  shipping_address VARCHAR(250) NOT NULL,
  total VARCHAR(250) NOT NULL
);