DROP TABLE IF EXISTS TBL_ORDERITEM;
  
CREATE TABLE TBL_ORDERITEM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_code VARCHAR(250) NOT NULL,
  product_name VARCHAR(250) NOT NULL,
  quantity VARCHAR(250) DEFAULT NULL
);